"use strict";this.default_openwindow=this.default_openwindow||{};(function(_){var window=this;
try{
_.aa=_.aa||{};_.h=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.k=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
try{
var ca,da;_.m=function(a){return void 0!==a};ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};da=function(a,b,c){return a.call.apply(a.bind,arguments)};
_.ea=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.p=function(a,b){function c(){}c.prototype=b.prototype;a.w=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ff=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};_.q=function(a,b,c){_.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return _.q.apply(null,arguments)};
_.fa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.ga=function(a){return"function"==_.ea(a)};_.ha=function(a){return"number"==typeof a};_.r=function(a){return"string"==typeof a};_.t=function(a){return"array"==_.ea(a)};_.ia=function(a){a.S=function(){return a.Mc?a.Mc:a.Mc=new a}};_.ja=function(){};_.ka=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.ka);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.p(_.ka,Error); _.ka.prototype.name="CustomError";
var la,ma;la=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
_.na=function(a,b){for(var c=0,d=la(String(a)).split("."),e=la(String(b)).split("."),f=Math.max(d.length,e.length),l=0;0==c&&l<f;l++){var n=d[l]||"",s=e[l]||"",w=RegExp("(\\d*)(\\D*)","g"),U=RegExp("(\\d*)(\\D*)","g");do{var Z=w.exec(n)||["","",""],ra=U.exec(s)||["","",""];if(0==Z[0].length&&0==ra[0].length)break;c=ma(0==Z[1].length?0:(0,window.parseInt)(Z[1],10),0==ra[1].length?0:(0,window.parseInt)(ra[1],10))||ma(0==Z[2].length,0==ra[2].length)||ma(Z[2],ra[2])}while(0==c)}return c}; ma=function(a,b){return a<b?-1:a>b?1:0};
_.u=Array.prototype;_.oa=_.u.indexOf?function(a,b,c){return _.u.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.r(a))return _.r(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.pa=_.u.lastIndexOf?function(a,b,c){return _.u.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.r(a))return _.r(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.v=_.u.forEach?function(a,b,c){_.u.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.r(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.qa=_.u.filter?function(a,b,c){return _.u.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,l=_.r(a)?a.split(""):a,n=0;n<d;n++)if(n in l){var s=l[n];b.call(c,s,n,a)&&(e[f++]=s)}return e};_.sa=_.u.reduce?function(a,b,c,d){d&&(b=(0,_.q)(b,d));return _.u.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,_.v)(a,function(c,l){e=b.call(d,e,c,l,a)});return e};
_.ta=_.u.some?function(a,b,c){return _.u.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.r(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.ua=function(a,b){var c=(0,_.oa)(a,b),d;(d=0<=c)&&_.u.splice.call(a,c,1);return d};
_.va=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;t:{var xa=_.h.navigator;if(xa){var ya=xa.userAgent;if(ya){_.wa=ya;break t}}_.wa=""}_.za=function(a){return-1!=_.wa.indexOf(a)};var Aa=function(a){_.h.setTimeout(function(){throw a;},0)},Ba,Ca=function(){var a=_.h.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,
a=(0,_.q)(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.za("Trident")&&!_.za("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.m(c.next)){c=c.next;var a=c.uc;c.uc=null;a()}};return function(a){d.next={uc:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")? function(a){var b=window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.h.setTimeout(a,0)}};
var Ia=function(a,b){Da||Ea();Fa||(Da(),Fa=!0);Ga.push(new Ha(a,b))},Da,Ea=function(){if(_.h.Promise&&_.h.Promise.resolve){var a=_.h.Promise.resolve();Da=function(){a.then(Ja)}}else Da=function(){var a=Ja;!_.ga(_.h.setImmediate)||_.h.Window&&_.h.Window.prototype.setImmediate==_.h.setImmediate?(Ba||(Ba=Ca()),Ba(a)):_.h.setImmediate(a)}},Fa=!1,Ga=[],Ja=function(){for(;Ga.length;){var a=Ga;Ga=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Aa(d)}}}Fa=!1},Ha=function(a,b){this.a= a;this.b=b};
_.Ka="StopIteration"in _.h?_.h.StopIteration:Error("e");var La,Pa,Sa,Ua,Va,Wa,Ya;La=_.za("Opera")||_.za("OPR");_.Ma=_.za("Trident")||_.za("MSIE");_.Na=_.za("Gecko")&&-1==_.wa.toLowerCase().indexOf("webkit")&&!(_.za("Trident")||_.za("MSIE"));_.Oa=-1!=_.wa.toLowerCase().indexOf("webkit");Pa=_.h.navigator||null;_.Qa=Pa&&Pa.platform||"";_.Ra=-1!=_.Qa.indexOf("Mac");Sa=_.h.navigator||null;_.Ta=!!Sa&&-1!=(Sa.appVersion||"").indexOf("X11");Ua=function(){var a=_.h.document;return a?a.documentMode:void 0};
Va=function(){var a="",b;if(La&&_.h.opera)return a=_.h.opera.version,_.ga(a)?a():a;_.Na?b=/rv\:([^\);]+)(\)|;)/:_.Ma?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:_.Oa&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(_.wa))?a[1]:"");return _.Ma&&(b=Ua(),b>(0,window.parseFloat)(a))?String(b):a}();Wa={};_.Xa=function(a){return Wa[a]||(Wa[a]=0<=_.na(Va,a))};Ya=_.h.document;_.Za=Ya&&_.Ma?Ua()||("CSS1Compat"==Ya.compatMode?(0,window.parseInt)(Va,10):5):void 0;
_.x=function(){this.I=this.I;this.j=this.j};_.x.prototype.I=!1;_.x.prototype.ac=function(){return this.I};_.x.prototype.H=function(){this.I||(this.I=!0,this.A())};_.x.prototype.A=function(){if(this.j)for(;this.j.length;)this.j.shift()()};_.$a=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};_.ab=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var fb,db,gb,kb;_.cb=function(a,b){this.b=0;this.g=void 0;this.a=this.c=null;this.j=this.e=!1;try{var c=this;a.call(b,function(a){bb(c,2,a)},function(a){bb(c,3,a)})}catch(d){bb(this,3,d)}};_.cb.prototype.then=function(a,b,c){return db(this,_.ga(a)?a:null,_.ga(b)?b:null,c)};_.$a(_.cb);_.cb.prototype.f=function(a){0==this.b&&Ia(function(){var b=new _.eb(a);fb(this,b)},this)};
fb=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,l;l=c.a[f];f++)if(l=l.Fa)if(d++,l==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?fb(c,b):(d=c.a.splice(e,1)[0],gb(c,d,3,b)))}}else bb(a,3,b)};_.ib=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||hb(a);a.a||(a.a=[]);a.a.push(b)};
db=function(a,b,c,d){var e={Fa:null,dc:null,ec:null};e.Fa=new _.cb(function(a,l){e.dc=b?function(c){try{var e=b.call(d,c);a(e)}catch(w){l(w)}}:a;e.ec=c?function(b){try{var e=c.call(d,b);!_.m(e)&&b instanceof _.eb?l(b):a(e)}catch(w){l(w)}}:l});e.Fa.c=a;_.ib(a,e);return e.Fa};_.cb.prototype.h=function(a){this.b=0;bb(this,2,a)};_.cb.prototype.k=function(a){this.b=0;bb(this,3,a)};
var bb=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(_.ab(c)){a.b=1;c.then(a.h,a.k,a);return}if(_.fa(c))try{var d=c.then;if(_.ga(d)){jb(a,c,d);return}}catch(e){b=3,c=e}}a.g=c;a.b=b;hb(a);3!=b||c instanceof _.eb||kb(a,c)}},jb=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.h(b))},f=function(b){d||(d=!0,a.k(b))};try{c.call(b,e,f)}catch(l){f(l)}},hb=function(a){a.e||(a.e=!0,Ia(a.l,a))};
_.cb.prototype.l=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)gb(this,a[b],this.b,this.g)}this.e=!1};gb=function(a,b,c,d){if(2==c)b.dc(d);else{if(b.Fa)for(;a&&a.j;a=a.c)a.j=!1;b.ec(d)}};kb=function(a,b){a.j=!0;Ia(function(){a.j&&_.lb.call(null,b)})};_.lb=Aa;_.eb=function(a){_.ka.call(this,a)};_.p(_.eb,_.ka);_.eb.prototype.name="cancel";
var mb=!_.Ma||_.Ma&&9<=_.Za,nb=_.Ma&&!_.Xa("9");!_.Oa||_.Xa("528");_.Na&&_.Xa("1.9b")||_.Ma&&_.Xa("8")||La&&_.Xa("9.5")||_.Oa&&_.Xa("528");_.Na&&!_.Xa("8")||_.Ma&&_.Xa("9");_.y=function(a,b){this.type=a;this.b=this.target=b;this.c=!1;this.Yc=!0};_.y.prototype.H=function(){};_.y.prototype.e=function(){this.c=!0};_.y.prototype.j=function(){this.Yc=!1};var ob=function(a){ob[" "](a);return a};ob[" "]=_.ja;_.pb=function(a,b){try{return ob(a[b]),!0}catch(c){}return!1};var qb=function(a,b){_.y.call(this,a?a.type:"");this.b=this.target=null;this.g=this.clientY=this.clientX=0;this.a=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.b=b;var c=a.relatedTarget;c&&_.Na&&_.pb(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.g=a.keyCode||0;this.state=a.state;this.a=a;a.defaultPrevented&&this.j()}};_.p(qb,_.y);
qb.prototype.e=function(){qb.w.e.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};qb.prototype.j=function(){qb.w.j.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,nb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var rb,tb;rb="closure_listenable_"+(1E6*Math.random()|0);_.sb=function(a){return!(!a||!a[rb])};tb=0;var ub=function(a,b,c,d,e){this.Ca=a;this.proxy=null;this.src=b;this.type=c;this.Ta=!!d;this.vb=e;this.key=++tb;this.removed=this.lb=!1},vb=function(a){a.removed=!0;a.Ca=null;a.proxy=null;a.src=null;a.vb=null};var wb=function(a){this.src=a;this.a={};this.b=0},xb;wb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var l=xb(a,b,d,e);-1<l?(b=a[l],c||(b.lb=!1)):(b=new ub(b,this.src,f,!!d,e),b.lb=c,a.push(b));return b};wb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=xb(e,b,c,d);return-1<b?(vb(e[b]),_.u.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var yb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=_.ua(a.a[c],b);d&&(vb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};wb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,vb(d[e]);delete this.a[c];this.b--}return b};_.zb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=xb(a,c,d,e));return-1<b?a[b]:null}; xb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.Ca==b&&f.Ta==!!c&&f.vb==d)return e}return-1};
var Ab,Bb,Cb,Ib,Jb,Ob,Nb,Kb,Pb;Ab="closure_lm_"+(1E6*Math.random()|0);Bb={};Cb=0;_.Db=function(a,b,c,d,e){if(_.t(b)){for(var f=0;f<b.length;f++)_.Db(a,b[f],c,d,e);return null}c=_.Fb(c);return _.sb(a)?a.listen(b,c,d,e):_.Gb(a,b,c,!1,d,e)};_.Gb=function(a,b,c,d,e,f){if(!b)throw Error("g");var l=!!e,n=_.Hb(a);n||(a[Ab]=n=new wb(a));c=n.add(b,c,d,e,f);if(c.proxy)return c;d=Ib();c.proxy=d;d.src=a;d.Ca=c;a.addEventListener?a.addEventListener(b.toString(),d,l):a.attachEvent(Jb(b.toString()),d);Cb++;return c};
Ib=function(){var a=Kb,b=mb?function(c){return a.call(b.src,b.Ca,c)}:function(c){c=a.call(b.src,b.Ca,c);if(!c)return c};return b};_.Lb=function(a,b,c,d,e){if(_.t(b))for(var f=0;f<b.length;f++)_.Lb(a,b[f],c,d,e);else c=_.Fb(c),_.sb(a)?a.kc(b,c,d,e):a&&(a=_.Hb(a))&&(b=_.zb(a,b,c,!!d,e))&&_.Mb(b)};
_.Mb=function(a){if(_.ha(a)||!a||a.removed)return!1;var b=a.src;if(_.sb(b))return yb(b.ca,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ta):b.detachEvent&&b.detachEvent(Jb(c),d);Cb--;(c=_.Hb(b))?(yb(c,a),0==c.b&&(c.src=null,b[Ab]=null)):vb(a);return!0};Jb=function(a){return a in Bb?Bb[a]:Bb[a]="on"+a};Ob=function(a,b,c,d){var e=1;if(a=_.Hb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ta==c&&!f.removed&&(e&=!1!==Nb(f,d))}return Boolean(e)};
Nb=function(a,b){var c=a.Ca,d=a.vb||a.src;a.lb&&_.Mb(a);return c.call(d,b)};
Kb=function(a,b){if(a.removed)return!0;if(!mb){var c;if(!(c=b))t:{c=["window","event"];for(var d=_.h,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new qb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(l){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.b;f;f=f.parentNode)e.push(f);for(var f=a.type,n=e.length-1;!c.c&&0<=n;n--)c.b=e[n],d&=Ob(e[n],f,!0,c);for(n=0;!c.c&&n<e.length;n++)c.b=e[n],d&=Ob(e[n],
f,!1,c)}return d}return Nb(a,new qb(b,this))};_.Hb=function(a){a=a[Ab];return a instanceof wb?a:null};Pb="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Fb=function(a){if(_.ga(a))return a;a[Pb]||(a[Pb]=function(b){return a.handleEvent(b)});return a[Pb]};
_.z=function(){_.x.call(this);this.ca=new wb(this);this.Y=this;this.g=null};_.p(_.z,_.x);_.z.prototype[rb]=!0;_.g=_.z.prototype;_.g.bb=function(a){this.g=a};_.g.addEventListener=function(a,b,c,d){_.Db(this,a,b,c,d)};_.g.removeEventListener=function(a,b,c,d){_.Lb(this,a,b,c,d)};_.g.A=function(){_.z.w.A.call(this);this.ca&&this.ca.removeAll(void 0);this.g=null};_.g.listen=function(a,b,c,d){return this.ca.add(String(a),b,!1,c,d)};_.g.rb=function(a,b,c,d){return this.ca.add(String(a),b,!0,c,d)};
_.g.kc=function(a,b,c,d){return this.ca.remove(String(a),b,c,d)};_.g.J=function(a,b,c){a=this.ca.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ta==b){var l=f.Ca,n=f.vb||f.src;f.lb&&yb(this.ca,f);d=!1!==l.call(n,c)&&d}}return d&&0!=c.Yc};
var Qb=function(){};Qb.prototype.a=null;var Sb;Sb=function(){};_.p(Sb,Qb);_.Rb=new Sb;var Tb,Ub,Vb,Wb,Xb,Yb,Zb;Zb=Yb=Xb=Wb=Vb=Ub=Tb=!1;var $b=_.wa;$b&&(-1!=$b.indexOf("Firefox")?Tb=!0:-1!=$b.indexOf("Camino")?Ub=!0:-1!=$b.indexOf("iPhone")||-1!=$b.indexOf("iPod")?Vb=!0:-1!=$b.indexOf("iPad")?Wb=!0:-1!=$b.indexOf("Chrome")?Yb=!0:-1!=$b.indexOf("Android")?Xb=!0:-1!=$b.indexOf("Safari")&&(Zb=!0));var ac=Tb,bc=Ub,cc=Vb,dc=Wb,ec=Xb,fc=Yb,gc=Zb;
var hc;hc=function(a){return(a=a.exec(_.wa))?a[1]:""};_.ic=function(){if(ac)return hc(/Firefox\/([0-9.]+)/);if(_.Ma||La)return Va;if(fc)return hc(/Chrome\/([0-9.]+)/);if(gc)return hc(/Version\/([0-9.]+)/);if(cc||dc){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.wa))return a[1]+"."+a[2]}else{if(ec)return(a=hc(/Android\s+([0-9.]+)/))?a:hc(/Version\/([0-9.]+)/);if(bc)return hc(/Camino\/([0-9.]+)/)}return""}();
var jc=function(){};_.kc=function(){};_.p(_.kc,jc);_.ia(_.kc);_.kc.S();
}catch(e){_._DumpException(e)}
try{
window.addEventListener("message",function(a){0==window.chrome.runtime.getURL("").indexOf(a.origin)&&this.open.apply(this,JSON.parse(a.data))},!1);_.kc.S();
}catch(e){_._DumpException(e)}
}).call(this,this.default_openwindow);
// Google Inc.
