Registry.registerRaw("environment.js","0",function(){Context.domContentLoaded=!1;Context.loadHappened=!1;Context.domNodeInserted=!1;Context.props={};Context.adjustLogLevel=function(a){void 0!==a&&(logLevel=a);D|=60<=logLevel};var q=function(){var a={objs:{},push:function(b,c){0!==c&&1!==c&&(c=0);var d=Math.floor(19831206*Math.random()+1);a.objs[d]={fn:b,prio:c};return d},remove:function(b){delete a.objs[b]},get:function(b){for(var c=[],d=0;1>=d;d++)for(var h in a.objs)a.objs.hasOwnProperty(h)&&
(a.objs[h].prio!==d||void 0!==b&&h!=b||c.push(a.objs[h].fn));return void 0===b?c:c[0]},finalize:function(b){if(void 0===b){b=a.get();for(var c=0;c<b.length;c++)b[c]()}else return a.objs[b]&&(c=a.objs[b].fn(),delete a.objs[b]),c}};return a}();Context.adjustLogLevel();var J=function(a){return{}.toString.apply(a).match(/\s([a-z|A-Z]+)/)[1]},z=function(a,b){void 0==b&&(b=100);return b&&a&&(a==document||z(a.parentNode,b-1))},N=function(){var a=function(){};a.prototype={};return new a},Y=function(){var a=
N(),b=function(a,c,b,d,e,k){var f=b[d];b[d]=k&&"string"===typeof f?new Function(f):function(){return f.apply(e,arguments)};return c.apply(a,b)},c={setTimeout:{enhance:function(){return b(window,safeWindow.setTimeout,arguments,0,a,!0)}},setInterval:{enhance:function(){return b(window,safeWindow.setInterval,arguments,0,a,!0)}},close:{get:function(){return window.self==window.top?function(a){return X(a)}:window.close}},location:{get:!0,set:function(a){window.location.href=a}},clearInterval:{get:function(){return safeWindow.clearInterval}},
clearTimeout:{get:function(){return safeWindow.clearTimeout}},addEventListener:{enhance:function(){return b(window,safeWindow.addEventListener,arguments,1,a,!0)}},removeEventListener:{enhance:function(){return b(window,safeWindow.removeEventListener,arguments,1,a,!0)}}},d=function(c){return c==window?a:c},h=function(a,c,b,d){b||(b=a);var e=function(){var e=a[c].apply(b,arguments);d&&(e=d(e));return e};e.__proto__=a[c];e.prototype=a[c].prototype;return e},f=function(c){var b,d,e=null,e=function(e){b=
e;d=function(){return e.apply(a,arguments)};window[c]=d};a.__defineGetter__(c,function(){return void 0===b||d!==window[c]?window[c]:b});a.__defineSetter__(c,e)},g=function(c,b,e){var k,f=null,g=null,f="function"===typeof b.get?b.get:function(){e&&e.get_cb&&e.get_cb.apply(this,arguments);return void 0===k?d(window[c]):k};"function"===typeof b.set?g=b.set:b.get||(g=function(a){e&&e.set_cb&&e.set_cb.apply(this,arguments);k=a});f&&a.__defineGetter__(c,f);g&&a.__defineSetter__(c,g)};(function(){var a=
0,c=function(c){for(var b=a;b<c;b++)g(String(b),{get:!0});a=Math.max(c,a)};g("length",{},{get_cb:function(){c(window.frames.length)}});c(Math.max(window.frames.length,7))})();for(var e in c)c.hasOwnProperty(e)&&(Context.windowProps[e]=Context.windowProps[e]||!1!==c[e]);var k;for(e in Context.windowProps)if(Context.windowProps.hasOwnProperty(e)&&!1!==c[e]){k={};try{try{c[e]?c[e].wrap?(k.wrap=!0,k.that=c[e].that):c[e].direct?k.direct=!0:c[e].enhance?k.enhance=c[e].enhance:c[e].get&&(k.get=c[e].get,
k.set=c[e].set):"function"===typeof window[e]?Context.windowProps[e].proto?k.wrap=!0:k.direct=!0:"number"===typeof window[e]||"string"===typeof window[e]?k.get=!0:Context.windowProps[e].event&&Context.windowProps[e].proto?k.event=!0:k.direct=!0}catch(r){k.get=!0}k.direct?a[e]=d(window[e]):k.enhance?a[e]=k.enhance:k.event?f(e):k.get||k.set?g(e,k):k.wrap&&function(){var c=e;a[c]=h(window,c,k.that,d)}()}catch(t){console.warn("env: error while creating a new sandbox: "+t.message)}}A(a);return a},Z=function(a,
b,c,d,h){var f=null;try{var g=d.sandboxes[a.id];g.__TMbackref||(g.__TMbackref={});var e='arguments.callee.__tmid = { id: "'+a.id+'", run_at: "'+a.options.run_at+'", ns: "'+a.namespace+'" };\n',k=["context"],r=[void 0],t;for(t in d.elements[a.id])if(d.elements[a.id].hasOwnProperty(t)){var n=d.elements[a.id][t];n.name?n.overwrite?(k.push(n.name),r.push(n.value)):n.scriptid?(g.__TMbackref[n.name+"_"+n.scriptid]=n.value,k.push(n.name),r.push('context.__TMbackref["'+n.name+"_"+n.scriptid+'"]')):(g[n.name]=
n.value,k.push(n.name),r.push("context."+n.name)):D&&console.warn("env: WARN: unexpected item in props elem: "+JSON.stringify(n))}f=[e,"with (context) {\n(function(",k.join(","),") {try {\n",c,b,"\n} catch (e) {if (e.message && e.stack) {console.error(\"ERROR: Execution of script '",a.name,'\' failed! " + e.message);console.log(e.stack.replace(/(\\\\(eval at )?<anonymous>[: ]?)|([\\s.]*at TM_mEval[\\s\\S.]*)/g, ""));} else {console.error(e);}};\n}).apply(context, [',r.join(","),"]);}\n"].join("");
d=function(a,c){(new Function("context",f)).apply(c,[c])};h?h(d,[f,g]):d(f,g)}catch(l){chromeEmu.extension.sendMessage({method:"syntaxCheck",code:[c,b].join("")},function(e){var d="";if(e.errors){var d=c.split("\n").length-1,k="",f;for(f in e.errors){var g=e.errors[f];if(g&&0<=g.line&&g.reason)var h=g.line,k=k+[h>d?"script:":"require:"," (",g.code,") ",g.reason.replace(/.$/,"")," on line: ",h>d?h-d:h," at character: ",g.character,"\n"].join("")}d="JSHINT output:\n"+k}else d=b;f=l.stack?l.stack.replace(/(\\(eval at )?<anonymous>[: ]?)|([\s.]*at TM_mEval[\s\S.]*)/g,
""):"";D||e.errors?console.error("Syntax error @ '"+a.name+"'!\n##########################\n"+d+"##########################\n\n"+f):console.error("Syntax error @ '"+a.name+"'!\n\n",f);safeWindow.setTimeout(function(){D&&chromeEmu.extension.sendMessage({method:"copyToClipboard",data:{content:b,type:"test"},id:"42"},function(){});throw l;},1)})}},u=[],l={events:[],done:{},running:null},x=function(a,b,c,d){var h={attrChange:0,attrName:null,bubbles:!0,cancelBubble:!1,cancelable:!1,clipboardData:void 0,
currentTarget:null,defaultPrevented:!1,eventPhase:0,newValue:null,prevValue:null,relatedNode:null,returnValue:!0,srcElement:null,target:null,timeStamp:(new Date).getTime()};c="string"===typeof c?new Function(c):c;var f=new Event,g;for(g in h)f[g]=h[g];for(g in b)f[g]=b[g];f.type=a;c.apply(d,[f])},B=function(a){Context.loadHappened=!0;Context.domContentLoaded=!0;D&&console.log("env: DOMContentLoaded Event!");v()},C=function(a){Context.domNodeInserted||!D||console.log("env: first DOMNodeInserted Event!");
Context.loadHappened=!0;Context.domNodeInserted=!0;l&&l.events.push({event:a,domContentLoaded:Context.domContentLoaded})},E=function(a){Context.loadHappened=!0;D&&console.log("env: load Event!")},F=function(){safeDocument.removeEventListener("DOMNodeInserted",C,!1);safeDocument.removeEventListener("DOMContentLoaded",B,!1);safeDocument.removeEventListener("load",E,!1);safeWindow.removeEventListener("unload",F,!1);if(null!=q){for(var a=q.get(),b=0;b<a.length;b++)a[b]();q=null}chromeEmu.clean&&chromeEmu.clean()},
v=function(){for(var a=u.length;0<u.length;){var b=u.shift();try{safeWindow.setTimeout(b.fn,1)}catch(c){console.log("ERROR: Execution (loadListener) of script env "+b.name+" failed!"+c.message)}}return a},G=function(a,b){if(document.body)safeWindow.setTimeout(function(){a()},1);else{var c=function(){safeDocument.removeEventListener("load",c,!1);safeDocument.removeEventListener("DOMNodeInserted",c,!1);safeDocument.removeEventListener("DOMContentLoaded",c,!1);G(a,b)};safeDocument.addEventListener("load",
c,!1);safeDocument.addEventListener("DOMNodeInserted",c,!1);safeDocument.addEventListener("DOMContentLoaded",c,!1)}},$=function(a,b,c){u.push({fn:function(){a()},name:c});Context.domContentLoaded?v():D&&console.log("env: schedule for later events!")},A=function(a){var b=[];a.__addEventListener||(a.__addEventListener=a.addEventListener,a.__removeEventListener=a.removeEventListener,a.removeEventListener=function(a,b,h){"DOMNodeInserted"==a&&l&&l.running==b&&(l.running=null);this.__removeEventListener(a,
b,h)},a.addEventListener=function(a,d,h){var f=!0;if("load"==a||"DOMContentLoaded"==a||"DOMNodeInserted"==a){var g=null,e=this;try{g=H(arguments.callee)}catch(k){D&&console.error("env: Error: event "+a,k)}if(g){var r=null;"load"==a?Context.loadHappened&&(r=function(){x("load",{attrName:"null",newValue:"null",prevValue:"null",eventPhase:Event.AT_TARGET,attrChange:MutationEvent.ADDITION,target:document,relatedNode:document,srcElement:document},d,e)},f=!1,b.push(r)):"DOMContentLoaded"==a?Context.domContentLoaded&&
(r=function(){x("DOMContentLoaded",{attrName:"null",newValue:"null",prevValue:"null",eventPhase:Event.AT_TARGET,attrChange:MutationEvent.ADDITION,target:document,relatedNode:document,srcElement:document},d,e)},f=!1,b.splice(0,0,r)):"DOMNodeInserted"==a&&l&&!l.done[g]&&(l.done[g]=!0,r=function(){var b="document-start"!=g.run_at&&"document-body"!=g.run_at;l.running=d;a:if(l)for(var k=l.events.length,f=0;f<k;f++)if(b&&!l.events[f].domContentLoaded||x("DOMNodeInserted",{attrName:"",newValue:"",prevValue:"",
eventPhase:Event.AT_TARGET,target:l.events[f].event.target,relatedNode:l.events[f].event.relatedNode,srcElement:l.events[f].event.srcElement},d,e),!l.running)break a;l.running&&e.__addEventListener(a,d,h);l.running=null},b.push(r));r&&(safeWindow.setTimeout(function(){if(b.length){var a=b[0];b=b.slice(1);a()}},1),f=!1)}}f&&this.__addEventListener(a,d,h)},q.push(function(){a.removeEventListener=a.__removeEventListener;a.addEventListener=a.__addEventListener}));Context.windowProps.__addEventListener=
{proto:!0};Context.windowProps.__removeEventListener={proto:!0}},H=function(a,b){void 0===b&&(b=20);return 0==b?null:!a.__tmid&&a.caller?H(a.caller,b-1):a.__tmid},O=function(a){q.finalize(a)},L=function(a,b,c){var d=TM_context_id+"#"+a,h=null,h=q.push(function(){chromeEmu.extension.sendMessage({method:"unRegisterMenuCmd",name:a,id:d},function(a){})},1);chromeEmu.extension.sendMessage({method:"registerMenuCmd",name:a,id:TM_context_id,menuId:d,accessKey:c},function(d){d.run&&null!==h&&void 0!==q.get(h)?
(safeWindow.setTimeout(function(){b()},1),L(a,b,c)):null!==h&&(q.remove(h),h=null)});return h},P=function(a,b){var c=!1,d=null,h=chromeEmu.extension.connect("openInTab_"+TM_context_id);a&&0==a.search(/^\/\//)&&(a=window.location.protocol+a);h.onMessage.addListener(function(a){a.tabId?c&&f():a.close&&(c=!0,d&&(d(),d=void 0))});h.onDisconnect.addListener(function(){h=null});h.postMessage({method:"openInTab",details:{url:a,id:TM_context_id,options:b},id:TM_context_id});var f=function(){h&&h.postMessage({method:"closeTab",
id:TM_context_id})},g={close:function(){c?D&&console.debug("env: attempt to close already closed tab!"):(c=!0,f())}};g.__defineGetter__("closed",function(){return c});g.__defineGetter__("onclose",function(){return d});g.__defineSetter__("onclose",function(a){d=a});return g},Q=function(a,b){var c=!1,d="Object"===J(a)?a:{url:a,name:b};d.url&&"/"===d.url[0]&&(d.url=window.location.origin+d.url);var h=d.context;delete d.context;var f=chromeEmu.extension.connect("download_"+TM_context_id);f.postMessage({method:"download",
details:d,id:TM_context_id});var g=function(a,b){b=b||{};a&&!c&&safeWindow.setTimeout(function(){a.apply(b,[b])},1)};f.onMessage.addListener(function(a){try{a.data&&h&&(a.data.context=h),a.success?d.onload&&(a.data.responseXML&&(a.data.responseXML=safeWindow.unescape(a.data.responseXML)),g(d.onload,a.data)):a.progress?d.onprogress&&g(d.onprogress,a.data):a.timeout?d.ontimeout&&g(d.ontimeout,a.data):d.onerror&&g(d.onerror,a.data)}catch(b){console.log("env: Error: TM_download - ",b,d)}});return{abort:function(){c=
!0}}},R=function(a){var b=!1;a.url&&"/"===a.url[0]&&(a.url=window.location.origin+a.url);var c=a.context;delete a.context;var d=function(){var a={};Object.getOwnPropertyNames(XMLHttpRequest.__proto__).forEach(function(b){a[b]=!0});var b=function(){};Object.getOwnPropertyNames(XMLHttpRequest).forEach(function(c){a[c]||(b[c]=XMLHttpRequest[c])});return b}(),h=function(a,c){c=c||{};a&&!b&&safeWindow.setTimeout(function(){c.__proto__=d;a.apply(c,[c])},1)},f=function(b){if(b.response2&&a.responseType){var c,
d=a.responseType.toLowerCase(),e=b.response2;delete b.response2;var f=function(a){for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=e.charCodeAt(c);return b.buffer};"arraybuffer"==d?c=f(e):"blob"==d?c=new Blob([f(e)]):"json"==d&&(c=JSON.parse(e));c&&(b.response=c)}return b};if("FormData"!==J(a.data)){var g=chromeEmu.extension.connect("xhr_"+TM_context_id);g.postMessage({method:"xhr",details:a,id:TM_context_id});g.onMessage.addListener(function(b){try{b.data&&c&&(b.data.context=c),b.success?
a.onload&&(b.data.responseXML&&(b.data.responseXML=safeWindow.unescape(b.data.responseXML)),h(a.onload,f(b.data))):b.change?a.onreadystatechange&&h(a.onreadystatechange,b.data):b.progress?a.onprogress&&h(a.onprogress,b.data):b.timeout?a.ontimeout&&h(a.ontimeout,b.data):a.onerror&&h(a.onerror,b.data)}catch(d){console.log("env: Error: TM_xmlhttpRequest",d,a)}})}else{var e=new XMLHttpRequest;void 0===a.async&&(a.async=!0);e.open(a.method,a.url,a.async,a.user,a.password);if(a.headers)for(g in a.headers)e.setRequestHeader(g,
a.headers[g]);a.overrideMimeType&&e.overrideMimeType(a.overrideMimeType);a.responseType&&(e.responseType=a.responseType);"abort error load progress readystatechange timeout".split(" ").forEach(function(b){e["on"+b]=function(){var d="",f=a.url;if(2<e.readyState&&(d=e.getAllResponseHeaders(),4==e.readyState)){d&&(d=d.replace(/TM-finalURL\: .*[\r\n]{1,2}/,""));var g=e.getResponseHeader("TM-finalURL");g&&(f=g)}d={readyState:e.readyState,status:"",statusText:"",responseHeaders:d,finalUrl:f,context:c};
4==e.readyState&&(e.responseType&&""!=e.responseType?d.response=e.response:(d.responseText=e.responseText,d.responseXML=e.responseXML),d.status=e.status,d.statusText=e.statusText);h(a["on"+b],d)}});e.send(a.data)}return{abort:function(){b=!0}}},S=function(a,b){chromeEmu.extension.sendMessage({method:"installScript",url:a,id:TM_context_id},function(a){b&&b(a)})},X=function(a){chromeEmu.extension.sendMessage({method:"closeTab",id:TM_context_id},function(b){b.error&&console.warn(b.error);a&&a()})},aa=
function(a,b){var c=[],d=a.storage,h=a.script.uuid,f=a.script,g=null;(function(){g=chromeEmu.extension.connect("storageListener_"+TM_context_id);g.onMessage.addListener(function(a){if(a.storage)for(var c in a.storage.data)if(a.storage.data.hasOwnProperty(c)){var e=d.data[c];d.data[c]=a.storage.data[c];l(c,e,d.data[c],!0)}a.removed&&(d[a.removed]=b);a.error&&console.log("env: Error: storage listener... :(")});g.postMessage({method:"addStorageListener",uuid:h,id:TM_context_id})})();var e=function(a){g.postMessage({method:"saveStorageKey",
uuid:h,key:a,value:d.data[a],id:TM_context_id,ts:d.ts})},k=function(a,c,d){d===b&&(d=function(a){return a});var e=[],f=null;if(a&&a.length){var f={GM_info:!0},g;for(g in a)if(a.hasOwnProperty(g)){var h=a[g];f[h]=!0}}for(g in c)c.hasOwnProperty(g)&&(h=c[g],f&&!f[d(h.name)]||e.push(h));return e},l=function(a,b,d,e){if(b!=d)for(var f in c)if(c.hasOwnProperty(f)){var g=c[f];if(g&&g.key==a&&g.cb)try{g.cb(a,v(b),v(d),e)}catch(h){D&&console.warn("env: value change listener of '"+a+"' failed with: "+h.message)}}},
t=function(a,b){var d=0,e;for(e in c)c.hasOwnProperty(e)&&c[e].id>d&&(d=e.id);d++;c.push({id:d,key:a,cb:b});return d},n=function(a){for(var b in c)if(c.hasOwnProperty(b)&&c[b].id==a)return delete c[b],!0},u=function(a){var b=d.data[a];d.ts=(new Date).getTime();delete d.data[a];e(a);l(a,b,d.data[a],!1)},x=function(){var a=[],b;for(b in d.data)d.data.hasOwnProperty(b)&&a.push(b);return a},v=function(a,b){if("string"===typeof a){var c=a[0];a=a.substring(1);switch(c){case "b":return"true"===a;case "n":return Number(a);
case "o":try{return JSON.parse(a)}catch(d){console.log("env: parseValueFromStorage: "+d)}return b;default:return a}}else return b},z=function(a,b){return v(d.data[a],b)},A=function(a,b){var c=d.data[a],f=(typeof b)[0];switch(f){case "o":try{b=f+JSON.stringify(b)}catch(g){console.log(g);return}break;default:b=f+b}d.ts=(new Date).getTime();d.data[a]=b;e(a);l(a,c,d.data[a],!1)},B=function(a){for(var b in f.resources){var c=f.resources[b];if(c.name==a)return c.resText}return null},C=function(a){for(var b in f.resources){var c=
f.resources[b];if(c.name==a)return c.resURL}return null},E=function(a){console.log(a)},F=function(a){try{var b=safeDocument.createElement("style");b.textContent=a;(document.head||document.body||document.documentElement||document).appendChild(b);return b}catch(c){console.log("Error: env: adding style "+c)}},G=function(c,d,e,f,g){var h,k=null;d||(d=a.script.name);if(g){var l=typeof g;"number"===l?h=g:"object"===l&&(k=g.onclose,h=g.timeout)}e==b&&(e=a.script.icon?a.script.icon:a.script.icon64);chromeEmu.extension.sendMessage({method:"notification",
delay:h,msg:c,image:e,title:d,id:TM_context_id},function(a){a.clicked&&f&&f();k&&k(!0===a.clicked)})},H=function(a,b,c){var d=typeof b,e="text",f="text/plain";"object"===d?(b.type&&(e=b.type),b.mimetype&&(f=b.mimetype)):"string"===d&&(e=b);chromeEmu.extension.sendMessage({method:"copyToClipboard",data:{content:a,type:e,mimetype:f},id:TM_context_id},function(a){c&&c()})},T=function(a){chromeEmu.extension.sendMessage({method:"getTab",id:TM_context_id,uid:f.uuid},function(b){a&&a(b.data)})},K=function(a,
b){chromeEmu.extension.sendMessage({method:"setTab",id:TM_context_id,tab:a,uid:f.uuid},function(a){b&&b()})},U=function(a){chromeEmu.extension.sendMessage({method:"getTabs",id:TM_context_id,uid:f.uuid},function(b){a&&a(b.data)})},m=function(a,b){var c=window,d="__u__"+Math.floor(19831206*Math.random()+1),e=d+"_";c[d]=a;c[e]=b;var f=Context.eval('window["'+d+'"].apply(this, window["'+e+'"])');delete c[d];delete c[e];return f},p=[],w=null,s;for(s in f.grant)if(f.grant.hasOwnProperty(s)&&"none"===f.grant[s]){w=
m;break}var y=f.namespace+"_"+!!w;Context.props[y]===b&&(Context.props[y]={sandboxes:{},elements:{}},q.push(function(){Context.props[y]=null}));if(!w){p.push({name:"window",value:"context",overwrite:!0});var M={window:window};for(s in M)M.hasOwnProperty(s)&&function(){var a=s.replace(/^(.)/g,function(a){return a.toUpperCase()});p.push({name:"unsafe"+a,value:M[s]})}()}p.push({name:"CDATA",value:function(a){this.src=a;this.toXMLString=this.toString=function(){return this.src}}});p.push({name:"uneval",
value:function(a){try{return"\\$1 = "+JSON.stringify(a)+";"}catch(b){console.log(b)}}});p.push({name:"undefined",value:b});p.push({name:"define",value:b});p.push({name:"module",value:b});p.push({name:"console",value:console});w||(p.push({name:"cloneInto",value:function(a,b,c){return a}}),p.push({name:"exportFunction",value:function(a,c,d){d&&d.defineAs!==b&&(c[d.defineAs]=a);return a}}),p.push({name:"createObjectIn",value:function(a,c){var d={};c&&c.defineAs!==b&&(a[c.defineAs]=d);return d}}));m=
[];m.push({name:"TM_addStyle",value:F});m.push({name:"TM_deleteValue",value:u});m.push({name:"TM_listValues",value:x});m.push({name:"TM_getValue",value:z});m.push({name:"TM_log",value:E});m.push({name:"TM_registerMenuCommand",value:L});m.push({name:"TM_unregisterMenuCommand",value:O});m.push({name:"TM_openInTab",value:P});m.push({name:"TM_setValue",value:A});m.push({name:"TM_addValueChangeListener",value:t});m.push({name:"TM_removeValueChangeListener",value:n});m.push({name:"TM_xmlhttpRequest",value:R});
m.push({name:"TM_download",value:Q});m.push({name:"TM_setClipboard",value:H});m.push({name:"TM_getTab",value:T});m.push({name:"TM_setTab",value:K});m.push({name:"TM_saveTab",value:K});m.push({name:"TM_getTabs",value:U});m.push({name:"TM_installScript",value:S});m.push({name:"TM_notification",value:G});m.push({name:"TM_getResourceText",value:B,scriptid:f.id});m.push({name:"TM_getResourceURL",value:C,scriptid:f.id});var I=[],V=new function(){this.GM_addStyle=function(a){return F(a)};this.GM_deleteValue=
function(a){return u(a)};this.GM_listValues=function(){return x()};this.GM_getValue=function(a,b){return z(a,b)};this.GM_addValueChangeListener=function(a,b){return t(a,b)};this.GM_removeValueChangeListener=function(a){return n(a)};this.GM_log=function(a){return E(a)};this.GM_registerMenuCommand=function(a,b,c){return L(a,b,c)};this.GM_unregisterMenuCommand=function(a){return O(a)};this.GM_openInTab=function(a,b){return P(a,b)};this.GM_setValue=function(a,b){return A(a,b)};this.GM_xmlhttpRequest=
function(a){return R(a)};this.GM_download=function(){return Q.apply(this,arguments)};this.GM_getResourceText=function(a){return B(a)};this.GM_getResourceURL=function(a){return C(a)};this.GM_notification=function(a,b,c,d,e){return G(a,b,c,d,e)};this.GM_installScript=function(a,b){return S(a,b)};this.GM_getTab=function(a){return T(a)};this.GM_setTab=function(a,b){return K(a,b)};this.GM_saveTab=function(a){return K(a)};this.GM_getTabs=function(a){return U(a)};this.GM_setClipboard=function(a,b,c){return H(a,
b,c)};Object.defineProperties(this,{GM_info:{get:function(){var b={observers:1,id:1,enabled:1,hash:1,fileURL:1},c={script:{}},d;for(d in f)f.hasOwnProperty(d)&&!b[d]&&(c.script[d]=f[d]);b=f.options.updateURL||f.options.fileURL;c.script["run-at"]=f.options.override.run_at||f.options.run_at;c.script.excludes=f.options.override.orig_excludes;c.script.includes=f.options.override.orig_includes;c.script.matches=f.options.override.orig_includes;c.script.grant=f.grant;c.script.unwrap=!1;c.scriptMetaStr=a.header;
c.scriptSource=a.code;c.scriptWillUpdate=!!b;c.scriptUpdateURL=b;c.version=a.version;c.scriptHandler="Tampermonkey";c.isIncognito=Context.isIncognito;return c},enumerable:!0,configurable:!0}})},W=[];for(s in V)W.push({name:s,value:V[s]});I=I.concat(k(f.grant,m,function(a){return a.replace(/^TM_/,"GM_")}));I=I.concat(k(f.grant,W));p=p.concat(I);f.options.compat_prototypes&&(D&&console.log("env: option: add toSource"),Object.prototype.toSource||Object.defineProperties(Object.prototype,{toSource:{value:function(){var a=
J(this);if("String"===a)return"(String('"+this.replace(/\'/g,"\\'")+"'))";if("Number"===a)return"(Number('"+Number(this)+"'))";if("Array"===a){for(var b="(new Array(",c=0;c<this.length;c++)a=J(this[c]),b="Null"===a?b+"null":"Undefined"===a?b+"undefined":b+this[c].toSource(),c+1<this.length&&(b+=",");return b+"))"}return"JSON.parse(unescape('"+safeWindow.escape(JSON.stringify(this))+"'))"},enumerable:!1,writable:!0,configurable:!0}}),D&&console.log("env: option: add some array generics"),"indexOf lastIndexOf filter forEach every map some slice".split(" ").forEach(function(a){if("function"!==
typeof Array[a]){var b={};b[a]={value:function(b){return Array.prototype[a].apply(b,Array.prototype.slice.call(arguments,1))},enumerable:!1,writable:!0,configurable:!0};Object.defineProperties(Array,b)}}));Context.props[y].sandboxes[a.script.id]=w?N():Y();Context.props[y].elements[a.script.id]=p;D&&console.debug("env: execute script "+f.name+" @ the "+(w?"un":"")+"safe context now!");Z(f,a.code,a.requires,Context.props[y],w);q.push(function(){g.postMessage({method:"removeStorageListener",uuid:h,storage:d,
id:TM_context_id});try{g.disconnect(),g=null}catch(b){}a=c=null})};chromeEmu.extension.onMessage.addListener(function(a,b,c){if(a.id&&a.id!=TM_context_id)console.warn("env: Not for me! "+TM_context_id+"!="+a.id);else if(b=window.self==window.top,"executeScript"==a.method)b=function(){aa(a);c({})},"document-start"==a.script.options.run_at?(D&&console.debug("env: run '"+a.script.name+"' ASAP -> document-start"),b()):"document-body"==a.script.options.run_at?(D&&console.debug("env: schedule '"+a.script.name+
"' for document-body"),G(b,a.script.id)):(D&&console.debug("env: schedule '"+a.script.name+"' for document-end"),$(b,a.script.id,a.script.name));else if("onLoad"==a.method){Context.domContentLoaded=!0;v();c({});var d=null,h=function(){l=d=null};q.push(function(){d&&safeWindow.clearTimeout(d);h()});d=safeWindow.setTimeout(h,2E3)}else b&&("loadUrl"==a.method?(window.location=a.url,c({})):"reload"==a.method?(window.location.reload(),c({})):"confirm"==a.method?safeWindow.setTimeout(function(){var b=safeWindow.confirm(a.msg);
c({confirm:b})},100):"showMsg"==a.method?safeWindow.setTimeout(function(){safeWindow.setTimeout(function(){safeWindow.alert(a.msg)},1);c({})},100):console.log("env: unknown method "+a.method))});(function(a){a.__evaluate||(a.__evaluate=a.evaluate,a.evaluate=function(a,c,d,h,f){c||(c=this);var g;if("undefined"!=typeof XPathResult){try{g=this.__evaluate(a,c,d,h,f)}catch(e){}var k=!0;try{k&=!g.snapshotLength}catch(l){}try{k&=!g.singleNodeValue}catch(q){}if(k&&"."!=a.charAt(0)&&!z(c)){a=("/"==a.charAt(0)?
".":"./")+a;try{g=this.__evaluate(a,c,d,h,f)}catch(n){}}}else g=c.selectNodes(a);return g},q.push(function(){a.evaluate=a.__evaluate}))})(window.HTMLDocument.prototype);A(window.HTMLDocument.prototype);safeDocument.addEventListener("DOMNodeInserted",C,!1);safeDocument.addEventListener("DOMContentLoaded",B,!1);safeDocument.addEventListener("load",E,!1);safeWindow.addEventListener("unload",F,!1);D&&console.debug("env: initialized (content, id:"+TM_context_id+", "+window.location.origin+window.location.pathname+
") ")});
